### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by PLUCS2** [PedroKim/facebookLite#1]
- General 
- [x] Add time estimates to each MVP
- User Auth 
- [x] Logged in users do not have access to the login or signup page 
- Profile 
- [x] Users should be able to post to their own wall 
- Posting/commenting 
- [x] Allows users to post on other's walls and comment on other's posts  
- [x] Cannot post to the wall of someone that is not a friend 
- News Feed 
- [x] Shows only friends posts 
- [x] News feed allows comments and links to post show pages/modals

**Comment by PedroKim** [comment]
Finished addressing these issues.
