### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by PLUCS2** [PedroKim/facebookLite#2]
- Users 
- [x] Users should have columns for first and last name
- [x] Email should be unique 
- Comments 
- [x] Add a parent_id column in case they are commenting on a comment 
- Profile
- [x] What was the motivation for splitting profile from user table?
- [x] check phone number markdown formatting 
- Other 
- [ ] add a likes table

**Comment by PedroKim** [comment]
Addressed all the issues except for likes. Likes is a bonus feature, which I intend to add once I'm done with MVP list.
