### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by PLUCS2** [PedroKim/facebookLite#4]
- [x] Users route should have some wildcard (which user profile informationa are you trying to fetch)
- [x] Users should possibly have a route to update user 
- [x] Should comments be nested under posts? How will the comment know which post/comment it is commenting on 
- [ ] add likes

**Comment by PedroKim** [comment]
Addressed all the issues. Planning to add likes portion when I get to bonus portion that contains likes.
